# Generated by Django 4.2.7 on 2024-01-20 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_userwallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='razor_pay_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
