# Generated by Django 4.2.7 on 2024-01-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_payment_razor_pay_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='signature_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
