# Generated by Django 4.2.7 on 2024-02-05 05:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
